### ISSUE TITLE
Segfault in BitVectorCache::populate

### ISSUE THREAD

**Issue by zhaakhi** [vespa-engine/vespa#12675]
Hi,

We have been observing some rare segmentation faults on our content nodes that appear to be coming from the BitVectorCache code.

This is currently with Vespa 7.169.4-1 running on CentOS.

I don't have any reproduction steps or confirmation on the newest version yet, but I thought I'd share the stacktrace just in case it's helpful.

Example stacktrace from `gdb --batch -ex bt /opt/vespa/sbin/vespa-proton-bin core.1234`
```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/vespa/sbin/vespa-proton-bin --identity [...]'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f112d978b92 in search::BitVectorCache::populate(vespalib::hash_map<unsigned long, search::BitVectorCache::KeyMeta, vespalib::hash<unsigned long>, std::equal_to<void>, vespalib::hashtable_base::prime_modulator>&, search::CondensedBitVector&, search::PopulateInterface const&) () at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/common/bitvectorcache.cpp:156
156	            for (int32_t docId(iterator->getNext()); docId >= 0; docId = iterator->getNext()) {
#0  0x00007f112d978b92 in search::BitVectorCache::populate(vespalib::hash_map<unsigned long, search::BitVectorCache::KeyMeta, vespalib::hash<unsigned long>, std::equal_to<void>, vespalib::hashtable_base::prime_modulator>&, search::CondensedBitVector&, search::PopulateInterface const&) () at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/common/bitvectorcache.cpp:156
#1  0x00007f112d978de9 in search::BitVectorCache::populate(unsigned int, search::PopulateInterface const&) () at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/common/bitvectorcache.cpp:174
#2  0x00007f112d935dc2 in search::PredicateAttribute::onCommit (this=0x10001514000) at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/attribute/predicate_attribute.cpp:100
#3  0x00007f112d74fc16 in search::AttributeVector::commit (this=this@entry=0x10001514000, forceUpdateStat=forceUpdateStat@entry=false) at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/attribute/attributevector.cpp:158
#4  0x00007f112d74fd75 in search::AttributeVector::commit (this=this@entry=0x10001514000, firstSyncToken=firstSyncToken@entry=1171032766, lastSyncToken=lastSyncToken@entry=1171032766) at /usr/src/debug/vespa-7.169.4/searchlib/src/vespa/searchlib/attribute/attributevector.cpp:172
#5  0x0000000000670927 in applyPutToAttribute (attr=..., immediateCommit=<optimized out>, lid=1828527, fieldValue=..., serialNum=1171032766) at /usr/src/debug/vespa-7.169.4/searchcore/src/vespa/searchcore/proton/attribute/attribute_writer.cpp:111
#6  proton::(anonymous namespace)::PutTask::run() () at /usr/src/debug/vespa-7.169.4/searchcore/src/vespa/searchcore/proton/attribute/attribute_writer.cpp:299
#7  0x00007f112a3a1d45 in vespalib::ThreadStackExecutorBase::run() () at /usr/src/debug/vespa-7.169.4/vespalib/src/vespa/vespalib/util/threadstackexecutorbase.cpp:125
#8  0x00007f112a3850f9 in vespalib::unnamed_blocking_executor (worker=...) at /usr/src/debug/vespa-7.169.4/vespalib/src/vespa/vespalib/util/blockingthreadstackexecutor.cpp:7
#9  0x00007f1129f16bd3 in FastOS_ThreadInterface::Hook() () at /usr/src/debug/vespa-7.169.4/fastos/src/vespa/fastos/thread.cpp:260
#10 0x00007f1129f16d59 in FastOS_ThreadHook (arg=<optimized out>) at /usr/src/debug/vespa-7.169.4/fastos/src/vespa/fastos/thread.cpp:229
#11 0x00007f113189073b in mallocThreadProxy () at /usr/src/debug/vespa-7.169.4/vespamalloc/src/vespamalloc/malloc/threadproxy.cpp:64
#12 0x00007f1129ae0e65 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f11248bf88d in clone () from /lib64/libc.so.6
```

**Comment by baldersheim** [comment]
We have never seen this kind of crash earlier on. I see that there is a missing sanity check in the code. So it is fully possible that we could be following the nullptr which is always bad. However if this happens there must be a logical flaw at a higher level.

Prior to the crash there should have have been logged som lines in the vespa.log file containing "Populating bitvector ...". Is it possible for you to gather those log lines and attach them here. Use 'vespa-logfmt -S searchnode [logfile]' to get the log lines for the vespa-proton-bin service. logfile is optional, if not given it will parse the current file. They are all found in $VESPA_HOME/logs/vespa.

I have made a guard against following the nullptr to avoid a crash. It will log an ERROR instead.
That will be present in upcomming 7.205 or 7.206 release due out just after easter.

**Comment by zhaakhi** [comment]
These are the log lines just before the crash - there are no recent log lines before this nor after before it restarts.

```[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  0 with feature 6230735685579922015 and 17 bits set. Cost is 3190827087.000000 = 42.15%, accumulated cost is 42.15%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  1 with feature 4118298484034562656 and 22 bits set. Cost is 2270670688.000000 = 30.00%, accumulated cost is 72.15%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  2 with feature 14612149835497511034 and 15 bits set. Cost is 1267251105.000000 = 16.74%, accumulated cost is 88.89%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  3 with feature 5123378521394602670 and 4 bits set. Cost is 130376516.000000 = 1.72%, accumulated cost is 90.61%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  4 with feature 14945161637013723056 and 6 bits set. Cost is 112069686.000000 = 1.48%, accumulated cost is 92.09%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  5 with feature 3466316167142785128 and 6 bits set. Cost is 102835014.000000 = 1.36%, accumulated cost is 93.45%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  6 with feature 13561805693493337591 and 5 bits set. Cost is 81442110.000000 = 1.08%, accumulated cost is 94.53%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  7 with feature 1985466717129769646 and 3 bits set. Cost is 54673044.000000 = 0.72%, accumulated cost is 95.25%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  8 with feature 3650067745207783105 and 3 bits set. Cost is 53674233.000000 = 0.71%, accumulated cost is 95.96%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector  9 with feature 5735558673184696940 and 3 bits set. Cost is 51088317.000000 = 0.67%, accumulated cost is 96.63%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 10 with feature 5294470480009415476 and 3 bits set. Cost is 51001941.000000 = 0.67%, accumulated cost is 97.31%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 11 with feature 13521457007982560936 and 3 bits set. Cost is 40236510.000000 = 0.53%, accumulated cost is 97.84%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 12 with feature 8768607287797394789 and 2 bits set. Cost is 33057150.000000 = 0.44%, accumulated cost is 98.27%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 13 with feature 9752354599241127435 and 1 bits set. Cost is 17638884.000000 = 0.23%, accumulated cost is 98.51%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 14 with feature 1811166287674169526 and 4 bits set. Cost is 16357772.000000 = 0.22%, accumulated cost is 98.72%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 15 with feature 4140831834368381742 and 4 bits set. Cost is 8148264.000000 = 0.11%, accumulated cost is 98.83%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 16 with feature 15520989785545222564 and 2 bits set. Cost is 5019696.000000 = 0.07%, accumulated cost is 98.90%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 17 with feature 10501326505477028953 and 4 bits set. Cost is 3523436.000000 = 0.05%, accumulated cost is 98.94%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 18 with feature 12253317433249305694 and 1 bits set. Cost is 2749664.000000 = 0.04%, accumulated cost is 98.98%
[2020-03-22 20:41:40.302] INFO    : searchnode       proton.searchlib.common.bitvectorcache	Populating bitvector 19 with feature 18415239477351610791 and 1 bits set. Cost is 2676831.000000 = 0.04%, accumulated cost is 99.02%
```

**Comment by baldersheim** [comment]
OK, thanks. Then it is an issue of counting bits at 2 different places in the code and not considering that the count can be reduced down to zero in between. The guard is then the proper solution.
Thanks, the fix has been merged and a new build will be published during the next 24 hours if all burn in tests pass.
Closing issue.
