### ISSUE TITLE
Unable to scale multiple configserver at once

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#17454]
Hi,

I tried multinode set up with 3 configserver, 3 container and 3 content. 
The configserver never come up and kept throwing error in zookeeper logs unexpected exception - java.lang.NullPointerException

Used case
1) Referred to GCE multinode set up
2) Passed single configserver host in env var  VESPA_CONFIGSERVERS via config map. statefulset pod scaled up.
3) Passed three configserver host (comma separated) in env var  VESPA_CONFIGSERVERS via config map. tried scaling statefulset pod with replica=3, the pod scale up got stuck with zookeeper error as unexpected exception - java.lang.NullPointer.exception.

###
VESPA_CONFIGSERVERS=myhost1.svc.cluster.local,myhost2.namepace.svc.cluster.local,myhost3.svc.cluster.local
where myhost1 myhost2 and myhost3 are <statefulset_index>.<headless_service>

Am I missing anything in multinode set up to spin up multiple config server at once?

**Comment by jobergum** [comment]
What do you mean by 
>Referred to GCE multinode set up 

Do you have the full exception?

**Comment by abhimech001** [comment]
> What do you mean by
> 
> > Referred to GCE multinode set up
> 
> Do you have the full exception?

https://github.com/vespa-engine/sample-apps/tree/master/basic-search-on-gke

config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: vespa-config
data:
  VESPA_CONFIGSERVERS: "vespa-0.vespa-internal.default.svc.cluster.local"

instead of one host used 3 as comma separarted
VESPA_CONFIGSERVERS: "vespa-0.vespa-internal.default.svc.cluster.local,vespa-1.vespa-internal.default.svc.cluster.local,vespa-2.vespa-internal.default.svc.cluster.local"

when tried to scale up master.yml with replicas=3, the vespa-0 configserver failed to start and gave null pointer exception in zookeeper logs.

**Comment by bratseth** [comment]
Could you share the exception stacktrace?

**Comment by abhimech001** [comment]
> Could you share the exception stacktrace?

We are using the docker image latest and while scaling config server with replica 2 as stateful object we are getting below error in zookeeper log.
Please use the zookeeper version from latest image version of vespa.

2021-02-08T12:42:08.229+0000 [myid:] - ERROR [nioEventLoopGroup-4-1:NettyServerCnxnFactory$CnxnChannelHandler@329] - Unexpected exception in receive
 java.lang.NullPointerException: null
         at org.apache.zookeeper.server.NettyServerCnxn.receiveMessage(NettyServerCnxn.java:518) ~[zookeeper-3.6.2.jar:3.6.2]
         at org.apache.zookeeper.server.NettyServerCnxn.processMessage(NettyServerCnxn.java:368) ~[zookeeper-3.6.2.jar:3.6.2]
         at org.apache.zookeeper.server.NettyServerCnxnFactory$CnxnChannelHandler.channelRead(NettyServerCnxnFactory.java:326) [zookeeper-3.6.2.jar:3.6.2]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.50.Final.jar:4.1.50.Final]
         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.50.Final.jar:4.1.50.Final]
         at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by bratseth** [comment]
From the ZK code this appears to be a symptom of failed leader election. My guess is you need to open some ports or something like that, but could you share what comes before this in the zookeeper log?

**Comment by abhimech001** [comment]
> From the ZK code this appears to be a symptom of failed leader election. My guess is you need to open some ports or something like that, but could you share what comes before this in the zookeeper log?

Hi Jon,

The exception only comes when we try to increase replicas of config server greater than 1. For single config server it works fine.

**Comment by bratseth** [comment]
Yes there's no leader election with just one config server. With more the config servers need to coordinate between themselves by communicating over ZooKeeper-specific connections (using Netty).

**Comment by abhimech001** [comment]
> Yes there's no leader election with just one config server. With more the config servers need to coordinate between themselves by communicating over ZooKeeper-specific connections (using Netty).

I was able to spin up multiple config server by updating the headless service with parameter "publishNotReadyAddress: true" to update DNS even if the pod is not up and ready.
Is it recommended?

**Comment by bratseth** [comment]
It's certainly not harmful in any way, so if it solves the problem it's 👍 
I guess what's happen here is that failing DNS resolution leads ZooKeeper down a path to an illegal internal state it cannot recover from. I'll update the sample app with this info - thanks!
