### ISSUE TITLE
vespa visit - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#18165]
Hi Team,

I am trying to dump all data of music content cluster to json file for backup and I am getting "java.lang.OutOfMemoryError: Java heap space"
Could you please review the error and suggest is it error from visit operation or content node and how can we tune it resolve issue and get higher throughput to dump data,
Requirement is to dump all data in json.

Run 1 -/opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> music.json

```Visiting all documents
Visiting bucket space: default
Visiting field set music:[document].
Tracking progress in file: progress-file
Let visitor have maximum 32 replies pending on data handlers per storage node visitor.
Visit maximum 1 buckets per visitor.
Visiting cluster '[Content:cluster=music]'.
Using visitor library 'DumpVisitor'.
Visitor priority LOW_1
Resuming visitor already 0.4 % finished.
Exception in thread "mbus.net-1-thread-2" java.lang.OutOfMemoryError: Java heap space
        at com.yahoo.slime.BufferedInput.getBytes(BufferedInput.java:77)
        at com.yahoo.slime.BinaryDecoder.decodeDATA(BinaryDecoder.java:97)
        at com.yahoo.slime.BinaryDecoder.decodeValue(BinaryDecoder.java:128)
        at com.yahoo.slime.BinaryDecoder.decodeValue(BinaryDecoder.java:138)
        at com.yahoo.slime.BinaryDecoder.decodeOBJECT(BinaryDecoder.java:116)
        at com.yahoo.slime.BinaryDecoder.decodeValue(BinaryDecoder.java:130)
        at com.yahoo.slime.BinaryDecoder.decodeValue(BinaryDecoder.java:138)
        at com.yahoo.slime.BinaryDecoder.decode(BinaryDecoder.java:22)
        at com.yahoo.slime.BinaryDecoder.decode(BinaryDecoder.java:16)
        at com.yahoo.slime.BinaryFormat.decode(BinaryFormat.java:64)
        at com.yahoo.messagebus.network.rpc.RPCSendV2.toParams(RPCSendV2.java:155)
        at com.yahoo.messagebus.network.rpc.RPCSend.doInvoke(RPCSend.java:168)
        at com.yahoo.messagebus.network.rpc.RPCSend.lambda$invoke$1(RPCSend.java:164)
        at com.yahoo.messagebus.network.rpc.RPCSend$$Lambda$84/0x000000084014a440.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"
Exception in thread "Vespa config thread" java.lang.OutOfMemoryError: Java heap space
Exception in thread "mbus.net-1-thread-1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4627)
        at com.yahoo.messagebus.MessageBus.sendBlockedMessages(MessageBus.java:92)
        at com.yahoo.messagebus.MessageBus$$Lambda$65/0x00000008400e4840.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "mbus.net-1-thread-3" java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "mbus.net-1-thread-5"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"```


Run 2 -/opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> music.json

```Visiting all documents
Visiting bucket space: default
Visiting field set music:[document].
Tracking progress in file: progress-file
Let visitor have maximum 32 replies pending on data handlers per storage node visitor.
Visit maximum 1 buckets per visitor.
Visiting cluster '[Content:cluster=music]'.
Using visitor library 'DumpVisitor'.
Visitor priority LOW_1
Resuming visitor already 0.4 % finished.
0.4 % finished.
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Vespa config thread"
Exception in thread "Thread-5" Exception in thread "Messenger" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
1623083337.686476       vespa-content-0.vespa-internal.default.svc.cluster.local        4168/25 -       vespa-visit.com.yahoo.jrt.Transport     error   fatal error in com.yahoo.jrt.TransportThread@7bdf04a1\nexception=\njava.lang.OutOfMemoryError: Java heap space\n```

**Comment by bratseth** [comment]
This is the local visitor running out of memory. Haven't seen that before, I guess we need to make a startup parameter for max memory for this, right now it's hardcoded to 1Gb.

Regardless, I recommend using document/v1 for visiting instead, for example GET /document/v1/?cluster=<clustername>, see https://docs.vespa.ai/en/reference/document-v1-api-reference.html. Then you can run it from anywhere that has connectivity.

**Comment by bratseth** [comment]
From the next release you can specify the -Xmx parameter to the visitor if your visitor needs more memory, e.g -Xmx2048 to double the default.
