### ISSUE TITLE
Model fails to configure storagenode and distributor

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#19429]
**Describe the bug**

Model seem to fail to setup distributor and storagenode and distributor in a specific setup. We are not able to reproduce but suspect that it could be related to OS/agent integrations?

services:

```
docker exec vespa bash -c '/opt/vespa/bin/vespa-model-inspect services'
config-sentinel
configproxy
configserver
container
container-clustercontroller
logd
logserver
metricsproxy-container
searchnode
slobrok
transactionlogserver
```

```
[2021-10-05 20:13:32.960] ERROR   : configserver     Container.com.yahoo.vespa.config.server.rpc.GetConfigProcessor
	Unexpected error handling config request
	exception=
	com.yahoo.config.ConfigurationRuntimeException: Unable to get config for default.default
	at com.yahoo.vespa.config.server.application.Application.createPayload(Application.java:169)
	at com.yahoo.vespa.config.server.application.Application.createConfigResponse(Application.java:135)
	at com.yahoo.vespa.config.server.application.Application.lambda$resolveConfig$1(Application.java:115)
	at com.yahoo.vespa.config.server.ServerCache.computeIfAbsent(ServerCache.java:62)
	at com.yahoo.vespa.config.server.application.Application.resolveConfig(Application.java:114)
	at com.yahoo.vespa.config.server.application.TenantApplications.resolveConfig(TenantApplications.java:210)
	at com.yahoo.vespa.config.server.rpc.RpcServer.resolveConfig(RpcServer.java:365)
	at com.yahoo.vespa.config.server.rpc.GetConfigProcessor.getConfig(GetConfigProcessor.java:114)
	at com.yahoo.vespa.config.server.rpc.GetConfigProcessor.run(GetConfigProcessor.java:147)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.lang.IllegalStateException: Requested port with offset 0 for service that has not reserved any ports: storagenode0 on host 'vespa-container'
	at com.yahoo.vespa.model.AbstractService.getRelativePort(AbstractService.java:221)
	at com.yahoo.vespa.model.content.ContentNode.getConfig(ContentNode.java:77)
	at com.yahoo.vespa.model.content.StorageNode.getConfig(StorageNode.java:97)
	at com.yahoo.vespa.config.content.core.StorCommunicationmanagerConfig$Builder.dispatchGetConfig(StorCommunicationmanagerConfig.java:202)
	at com.yahoo.config.model.producer.AbstractConfigProducer.cascadeConfig(AbstractConfigProducer.java:210)
	at com.yahoo.vespa.model.VespaModel.populateConfigBuilder(VespaModel.java:492)
	at com.yahoo.vespa.model.VespaModel.getConfig(VespaModel.java:487)
	at com.yahoo.vespa.model.VespaModel.resolveToBuilder(VespaModel.java:520)
	at com.yahoo.vespa.model.VespaModel.getConfigInstance(VespaModel.java:509)
	at com.yahoo.vespa.config.server.application.Application.createPayload(Application.java:142)
	... 13 more
```

**To Reproduce**
Only reproduces in an environment outside of our control https://docs.vespa.ai/en/vespa-quick-start.html

**Environment (please complete the following information):**
 - MacOS x86
 - GCP
 
Reproduced 
 

**Vespa version**
vespaengine/vespa:7.475.17

**Additional context**

**Comment by bratseth** [comment]
This is currently the result from deploying a cloud app in a self-hosted environment.
