### ISSUE TITLE
Unable to insert more than 500k data points

### ISSUE THREAD

**Issue by yazid-blackbird** [vespa-engine/vespa#19970]
**Describe the bug**
I try to insert 1M data point with a batch 1. After inserting about 500K, the code stops and complains with an HTTP error 104 reset by peer

**Error Trace**
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                                                                  
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send                                     
    timeout=timeout
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))                                                                                          
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /document/v1/image_search/image_search/docid/f6da3960e89e4d2b4e44d3fe0f5d325f80f475a4ec8781687468a8093324d3fe (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                                                                            
  File "../app/insert_data_id_hash.py", line 76, in <module>                                                                                                    
    rep =  vespa.insert(schema="image_search",data=data)                                                                                                      
  File "/home/ubuntu/workspace/vespa/app/vespa_engine_hash.py", line 33, in insert                                                                 
    return self.__vespa_client._feed_batch_sync(batch=batch, schema=schema)                                                                                   
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/vespa/application.py", line 278, in _feed_batch_sync                         
    for data_point in batch                                                                                                                                   
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/vespa/application.py", line 278, in <listcomp>                               
    for data_point in batch                                                                                                                                   
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/vespa/application.py", line 272, in feed_data_point                          
    schema=schema, data_id=data_id, fields=fields
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/vespa/application.py", line 984, in feed_data_point
    end_point, json=vespa_format, cert=self.app.cert
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/workspace/vespa/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /document/v1/image_search/image_search/docid/f6da3960e89e4d2b4e44d3fe0f5d325f80f475a4ec8781687468a8093324d3fe (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```
**Expected behavior**
 it should be able to insert without any problems

**Environment :**
 - OS: ubuntu 
 - Infrastructure:  AWS  m4.4xlarge
 - Versions 18.04

**Vespa version**
latest on docker

**Comment by kkraune** [comment]
Thanks for the report! an extract from vespa.log from the failing period is useful. @jonmv not sure what will cause a 104, I don't find it at https://docs.vespa.ai/en/reference/document-v1-api-reference.html

**Comment by jonmv** [comment]
That's from Jetty. Perhaps @bjorncs knows anything about it. I assume this is self-hosted? Anything between the client and the server?

**Comment by bjorncs** [comment]
The 104 response looks like a synthetic response created by the client to signal that the connection was closed by the peer.
The server will close any connection idling for more than 3 minutes. Are you able to send a request with e.g. curl after feed client fails? Please enable access logging on the container cluster and look for any suspicious entries (e.g non-200 responses, timeouts etc).
