### ISSUE TITLE
Importing Tensorflow model fails 

### ISSUE THREAD

**Issue by dj-shin-okcupid** [vespa-engine/vespa#21663]
**Describe the bug**

**To Reproduce**
1. Set up environment with Python 3.7.5 and tensorflow-cpu 2.4.1
2. Used sample application 'model-evaluation' as the base application
3. Follow instructions in https://github.com/vespa-engine/sample-apps/tree/master/model-evaluation
4. After downloading sample application to `myapp/`, go to `src/main/applications/models/`.
5. Run the following code in Python to create a saved model in the directory:
```
    import tensorflow as tf
    INPUT_DIM = 30
    FC_DEPTH = 3
    FC_WIDTH = 50
    input_layer = tf.keras.Input(INPUT_DIM, name='x')
    fc_layer = [tf.keras.layers.Dense(FC_WIDTH, activation='relu') for _ in range(FC_DEPTH)]
    output_layer = tf.keras.layers.Dense(1, name='y')
    model = tf.keras.Sequential([input_layer] + fc_layer + [output_layer])
    model.save('tf_test_model')
```
7. Run `mvn clean package -U`. Logs should already indicate that the Tensorflow model conversion to ONNX has failed.
8. Run `vespa deploy --wait 300`
9. See error

**Expected behavior**
Model loads into application and is deployed successfully.

**Screenshots**
This is the error log:
```
WARNING Skipping import of model tf_test_model as an exception occurred during import. Error: Unable to convert TensorFlow model in '/opt/vespa/var/db/vespa/config_server/serverdb/tenants/default/sessions/13/.preprocessed/models/tf_test_model' to ONNX. Reason: WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2022-03-11 16:14:30,080 - WARNING - From /usr/local/lib/python3.6/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2022-03-11 16:14:30,107 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2022-03-11 16:14:30,107 - WARNING - '--signature_def' not provided. Using all signatures.
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from dense_68/kernel:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/vespa/bin/vespa-convert-tf2onnx", line 97, in <module>
    main()
  File "/opt/vespa/bin/vespa-convert-tf2onnx", line 89, in main
    convert.main()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 285, in main
    output_path=args.output)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in _convert_common
    tf.import_graph_def(frozen_graph, name='')
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from dense_68/kernel:0 incompatible with expected resource.
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Infrastructure: Kubernetes, Azure, AWS, self-hosted
 - Versions 20.04

**Vespa version**
10.555.50

**Additional context**
None

**Comment by lesters** [comment]
Vespa uses [tf2onnx](https://github.com/onnx/tensorflow-onnx) to convert a model to ONNX before importing the model. The problem here is this model has been constructed with a newer version of TensorFlow (2.4.1) than the version installed in Vespa supports. 

I recommend converting the model to ONNX yourself using `tf2onnx` - and importing that model. This also ensures that the model will be evaluated as efficiently as possible using the underlying ONNX runtime accelerator.

We are phasing out support for TensorFlow in the next major version of Vespa, so this is the recommended route.
