### ISSUE TITLE
Unable to deploy application zip in vespa on bare metal open shift cluster 

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#21946]
**Describe the bug**
We are trying to deploy application zip to the vespa config server using the vespa-deploy command line but we keep getting 504 timed out error. Upon checking the vespa-logfmt logs we can not find any logs related to the application deployment. 
On closer analysis we found from the zookeeper logs that the zoo keeper is not starting on the config server. 

```
Zookeeper Logs : 
648827932.715038       vespa-0000-bm-ingest-all-schemas-0.vespa-0000-bm-ingest-all-schemas-internal.namespace.svc.cluster.local  440/94  -       .org.apache.curator.RetryLoopImpl       debug   Retry-able exception received
exception=
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /configserver/v1/locks/TenantsMaintainer/_c_0657a59d-7c83-4006-a2bc-48635d8246b5-lock-
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1450)
	at org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1216)
	at org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1193)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1190)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:573)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:48)
	at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)
	at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:225)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:237)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:108)
	at com.yahoo.vespa.curator.Lock.acquire(Lock.java:44)
	at com.yahoo.vespa.curator.Curator.lock(Curator.java:313)
	at com.yahoo.vespa.config.server.maintenance.ConfigServerMaintainer$JobControlFlags.lockMaintenanceJob(ConfigServerMaintainer.java:81)
	at com.yahoo.concurrent.maintenance.JobControl.lockJob(JobControl.java:59)
	at com.yahoo.concurrent.maintenance.Maintainer.lockAndMaintain(Maintainer.java:112)
	at com.yahoo.concurrent.maintenance.Maintainer.run(Maintainer.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

1648827932.713537       vespa-0000-bm-ingest-all-schemas-0.vespa-0000-bm-ingest-all-schemas-internal.namespace.svc.cluster.local  440/97  -       .org.apache.curator.RetryLoopImpl       debug   Retry-able exception received
exception=
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /config/v2/tenants/default/applications
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2480)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:242)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:231)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:228)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:219)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:41)
	at com.yahoo.vespa.curator.Curator.getChildren(Curator.java:269)
	at com.yahoo.vespa.config.server.application.ApplicationCuratorDatabase.activeApplications(ApplicationCuratorDatabase.java:121)
	at com.yahoo.vespa.config.server.application.TenantApplications.activeApplications(TenantApplications.java:111)
	at com.yahoo.vespa.config.server.ApplicationRepository.lambda$listApplications$18(ApplicationRepository.java:703)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.yahoo.vespa.config.server.ApplicationRepository.listApplications(ApplicationRepository.java:704)
	at com.yahoo.vespa.config.server.ApplicationRepository.getFileReferencesInUse(ApplicationRepository.java:628)
	at com.yahoo.vespa.config.server.ApplicationRepository.deleteUnusedFileDistributionReferences(ApplicationRepository.java:609)
	at com.yahoo.vespa.config.server.maintenance.FileDistributionMaintainer.maintain(FileDistributionMaintainer.java:42)
	at com.yahoo.concurrent.maintenance.Maintainer.lockAndMaintain(Maintainer.java:113)
	at com.yahoo.concurrent.maintenance.Maintainer.run(Maintainer.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Environment (please complete the following information):**
 - Infrastructure: OpenShift kubernetes
 - Versions [e.g. 22]: 7.559.12

**Vespa version**
7.559.12

**Additional context**
We have tried bringing up the cluster from scratch multiple times but still keep facing the issue.

**Comment by kkraune** [comment]
some info on how zookeeper is used in https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode

also see https://github.com/vespa-engine/sample-apps/blob/master/examples/operations/README.md#troubleshooting

**Comment by 107dipan** [comment]
We are running vespa clusters with one configserver on Vm based k8s clusters. On these our application deployment is working properly and also zookeeper is not throwing any exceptions.

We are facing these issues only with bare metal clusters based on OpenShift

**Comment by kkraune** [comment]
I assume then that the problem in this ticket is when using one config server, correct me if this is wrong

the zookeeper instance is running inside the config server, and it is indeed running, ref the log messages - but fail on acquiring a lock, maybe @hmusum would know.

please also provide the docker image used when running this, @107dipan

**Comment by 107dipan** [comment]
This is the Docker file we are using to create the docker image. We have added logic to add permission to some folders but we are not doing anything beside that. 


FROM <internal-dcoker-registry>/vespaengine/vespa:7.559.12


RUN chmod -R 755 /opt && \
chmod -R 755 /usr && \
chmod -R 755 /bin && \
chmod -R 755 /vespa-db

ENTRYPOINT ["/usr/local/bin/start-container-lex.sh"]

**Comment by hmusum** [comment]
Errors in log indicate that zookeeper server is down (ConnectionLoss). `FileDistributionMaintainer` is started after config server has successfully bootstrapped and is marked as up, so it looks like it has been shutdown again (?).

Please show what the request for ApplicationStatus in the troubleshooting doc (https://github.com/vespa-engine/sample-apps/blob/master/examples/operations/README.md#troubleshooting) returns. 

Also show log warning or errors (`vespa-logfmt -l warning,error`)

**Comment by 107dipan** [comment]
We are getting 504 error when deploying the application. We are not getting any error or warning logs when deploying the application. 
We can only see the errors from configproxy which are usually shown when the application is not deployed.

**Comment by hmusum** [comment]
Please show the response you get when deploying (all responses from Vespa config server includes an error code and error message in the json response) : Also show response from http:://host:19071/ApplicationStatus before deploying. 

There should be something in vespa log if deployment fails. There is also an access log (/opt/vespa/logs/vespa/configserver/acces-json<date>) and connection log (ConnectionLog.configserver.<date>) that should show something for these request. Are you sure you are actually deploying to the correct endpoint?

**Comment by 107dipan** [comment]
We are using the vespa-deploy prepare and activate to deploy our application. 
We are not getting output other than 504 http error. 
I will check acess-json. 

configserver is up and running 
bash-4.2$ curl -s http://localhost:19071/ApplicationStatus
{
  "application" : {
    "vespa" : {
      "version" : "7.559.12"
    },
    "meta" : {
      "name" : "standalone_container7878828057868332618",
      "user" : "n/a",
      "path" : "n/a",
      "generation" : 0,
      "timestamp" : 0,
      "date" : "Thu Jan 01 00:00:00 UTC 1970",
      "checksum" : ""
    },
    "user" : {
      "version" : ""
    }
  },

**Comment by hmusum** [comment]
Thanks, config server is up and running, good. Could you show the command you use to deploy with response and time stamps that show how long it took before response returned?  Access log entries would also be good.

**Comment by hmusum** [comment]
No response, cloding
