### ISSUE TITLE
Can't configure timeout for custom processor at feed time

### ISSUE THREAD

**Issue by viantirreau** [vespa-engine/vespa#25553]
**Describe the bug**

I keep hitting a 180s timeout, despite configuring the `service.xml` - container section to use a lower value, such as 10 seconds, as well as setting `vespa-feed-client` with the parameter `--timeout 10`. The problem is not in the documents _per se_, as it happens randomly when some `update` operations get bunched together, blocking all the feed queue consistently for 180 seconds. Also, the 180 value is kind of suspicious, as it is the default [document-api](https://docs.vespa.ai/en/reference/services-container.html#document-api) timeout.

**To Reproduce**
1. Use a custom processor that updates some document fields with a sync session. The relevant Java code goes along these lines:

```java
// Context: I am inserting a job offer that may be a duplicate of existing ones
// ... ^ here goes the logic to find a canonical offer, so I can detect and link semantic duplicates
Document representativeDoc = syncSession.get(representativeDocId, SYNC_TIMEOUT);
// after some digging, I tried using this overload for the `get` operation, with SYNC_TIMEOUT = 10 seconds,
// but the process still got stuck at the update some lines further down (for 180 seconds as usual)
logger.info("Fetched representative document " + representativeDocId + " for document " + offerId);
// the previous line always gets printed before the feed stops and times out
if (representativeDoc != null) {
  DocumentUpdate representativeUpdate = new DocumentUpdate(doc.getDataType(), representativeDocId);
  boolean alreadyInCurrentArray = false;
  // ... find this document id (offer id) inside the canonical document
  if (!alreadyInCurrentArray) {
    // ... update the representative (canonical) document to hold 
    // a reference to the one being currently inserted
    currentArray.add(toSaveInRepresentativeDoc);
    representativeUpdate.addFieldUpdate(FieldUpdate.createAssign(
      representativeDoc.getField("representative_of"),
      (FieldValue) (currentArray)));
    syncSession.update(representativeUpdate); // <- I think this is the operation that causes the timeout
    logger.info("Updated representative_of field in document " + representativeDocId);
    // because the previous line never gets printed before the feed stalls
}

```
The logic to search for duplicates in the HNSW index closely follows several sample apps, such as `billion-scale-vector-search` [AssignNeighborsDocProc](https://github.com/vespa-engine/sample-apps/blob/master/billion-scale-vector-search/src/main/java/ai/vespa/examples/docproc/AssignNeighborsDocProc.java). I use the same `async` strategy for fetching related documents. The only difference is that when I find an existing duplicate document in the index, that one is regarded as canonical, while the incoming one is considered the duplicate. 

As I need a bidirectional link (not an actual document link, just a plain old string array holding the IDs for which the canonical is `representative_of`, and a string for the `represented_by` attribute in the duplicate), I must update both the current document and the canonical one, hence the need for a sync session to fetch and update the canonical. I don't know if there's a better way to do this.

2. Configure the `document-api` section of the `container` in `services.xml` as follows:

```xml
        <document-api>
            <timeout>10.0</timeout>
        </document-api>
```
3. Use `vespa-feed-client` to feed documents, with the CLI argument `--timeout 10`
4. See timeout error in Vespa stdout

**Expected behavior**

To have the document put operation fail earlier, so that the retry logic in `vespa-feed-client` can kick in sooner. The whole feed operation blocks for 180 seconds while waiting for the timeout.

**Traceback**

<details>
<summary>Traceback of the timeout at feed time</summary>

```
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::JHmQmqJa-dn_gyotyqNbo. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::F1EuqoqBpfDU9GjZvlEc0. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::eEUTgCaWpndfMv6jw28TK. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::vv8H8xTo7X9TFARWc4_-A. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::tRRyiQTDPSVO28CSA_MQW. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::T-8eFlcfEhk9dQeI0dWUf. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.599] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::5uo2HDYTbTBZnWkOPKp-8. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [TIMEOUT @ localhost]: A timeout occurred while waiting for 'tcp/vespa-container:19100/chain.offer-processing' (180.0 seconds expired); Request timed out after 180.0 seconds. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
[2023-01-13 01:52:26.607] WARNING container        Container.com.yahoo.docproc.jdisc.DocumentProcessingTask	
	Processing of put of document id:offer:offer::1l5sZrkQNfFgPCU8U4YAk. Last call: call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing) failed at call to class processor.OfferDocumentProcessor (id: processor.OfferDocumentProcessor in offer-processing)
	exception=
	com.yahoo.documentapi.DocumentAccessException: [UNKNOWN(252001) @ tcp/vespa-container:19100/chain.offer-processing]: Time is up. 
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:190)
	at com.yahoo.documentapi.messagebus.MessageBusSyncSession.update(MessageBusSyncSession.java:182)
	at processor.OfferDocumentProcessor.process(OfferDocumentProcessor.java:287)
	at com.yahoo.docproc.Call.call(Call.java:154)
	at com.yahoo.docproc.impl.DocprocExecutor.process(DocprocExecutor.java:117)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.process(DocumentProcessingTask.java:120)
	at com.yahoo.docproc.jdisc.DocumentProcessingTask.run(DocumentProcessingTask.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Every `Processing of put of document id:offer:offer:: ...` line  contains the ID of a duplicate document, and I strongly suspect that the sync `update` on the canonical is responsible for the timeout, not the `get` operation. Documents for which no duplicates were found do not follow this code path, and their `put` is processed without any hiccups.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Infrastructure: self-hosted
 - Versions: `vespa:latest`, pulled today.

**Additional details**

Even though I increased the JVM heap size without a significant impact, I don't really mind having timeouts, as long as they are shorter. My use case allows for a lot of retries while feeding the documents.

Thanks in advance!

**Comment by bratseth** [comment]
A document sync session has its own timeout, which you set like this:

```
        var parameters = new SyncParameters.Builder();
        parameters.setDefaultTimeout(Duration.ofSeconds(10));
        SyncSession session = access().createSyncSession(parameters.build());
```

However, **don't** use a sync session here, document processing should be completely async. You could create an async session, kick off the operations, return Progress.LATER from the document processor, and then check for the responses when next invoked.

But since you're just changing the document operations to be performed as part of the processing, you can just do that directly. Replace the sync session call with 

```
        processing.addDocumentOperation(representativeUpdate);
```

**Comment by viantirreau** [comment]
Just changed that line and it worked flawlessly! Thanks so much @bratseth!! 🥳
