### ISSUE TITLE
pyvespa: connection reset not handled

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#27648]
Feed problems using pyvespa - per @jobergum:

> You are getting a connection reset which it looks like the underlaying http client used by pyvespa does not handle or retry:/ it’s expected that Vespa will recycle connections so that is really unfortunate.

---

```
Successful documents fed: 1000/1000.
Batch progress: 1/22.
Successful documents fed: 1000/1000.
Batch progress: 2/22.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4880' coro=<VespaAsync._feed_data_point_semaphore() done, defined at /home/jrs/anaconda3/lib/python3.9/site-packages/vespa/application.py:1090> exception=RetryError(<Future at 0x7fa286cac550 state=finished raised ClientOSError>)>
Traceback (most recent call last):
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 581, in write_bytes
    await self.body.write(writer)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/payload.py", line 247, in write
    await writer.write(self._value)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/http_writer.py", line 115, in write
    self._write(chunk)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/vespa/application.py", line 1082, in feed_data_point
    response = await self.aiohttp_session.post(end_point, json=vespa_format)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/jrs/anaconda3/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://localhost:8080/document/v1/ZZZ/YYY/docid/1234
```

**Comment by kkraune** [comment]
The following will reproduce the problem:

```
from vespa.package import ApplicationPackage, Field, FieldSet, RankProfile
from vespa.deployment import VespaDocker
from pandas import read_csv

app_package = ApplicationPackage(name="textsearch")

app_package.schema.add_fields(
    Field(name="id",    type="string", indexing=["attribute", "summary"]),
    Field(name="title", type="string", indexing=["index", "summary"], index="enable-bm25"),
    Field(name="body",  type="string", indexing=["index", "summary"], index="enable-bm25")
)

app_package.schema.add_field_set(
    FieldSet(name="default", fields=["title", "body"])
)

app_package.schema.add_rank_profile(
    RankProfile(name="bm25", first_phase="bm25(title) + bm25(body)")
)
app_package.schema.add_rank_profile(
    RankProfile(name="native_rank", first_phase="nativeRank(title, body)")
)

vespa_docker = VespaDocker()
app = vespa_docker.deploy(application_package=app_package)

docs = read_csv(
    filepath_or_buffer="https://data.vespa.oath.cloud/blog/msmarco/sample_docs.csv"
).fillna('')
docs.head()

for x in range(50):
    print("iteration: " + str(x))
    feed_res = app.feed_df(docs, asynchronous=True, batch_size=1000)
```

```
Batch progress: 7/10.
Successful documents fed: 1000/1000.
Batch progress: 8/10.
Successful documents fed: 1000/1000.
Batch progress: 9/10.
Successful documents fed: 963/963.
Batch progress: 10/10.
iteration: 28
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-615205' coro=<VespaAsync._feed_data_point_semaphore() done, defined at /Users/kraune/Library/Python/3.11/lib/python/site-packages/vespa/application.py:1092> exception=RetryError(<Future at 0x12a96ce50 state=finished raised TimeoutError>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kraune/Library/Python/3.11/lib/python/site-packages/vespa/application.py", line 1084, in feed_data_point
    response = await self.aiohttp_session.post(end_point, json=vespa_format)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

The above exception was the direct cause of the following exception:
```

**Comment by kkraune** [comment]
It seems to me that the async calls push enough load for items to time out eventually, and the workaround is to use `asynchronous=False` in the calls for now

**Comment by lesters** [comment]
Considered fixed with the above PR. Reopen if issue persists.
