### ISSUE TITLE
ArrayIndexOutOfBoundsException during feeding of large JSON Files containing multiple documents

### ISSUE THREAD

**Issue by asutoshprasad** [vespa-engine/vespa#32475]
I encountered an ArrayIndexOutOfBoundsException while feeding a large JSON file (approx 1GB) containing multiple json documents to a Vespa cluster. The error occurs during the batch feeding process. I am ingesting around 500 such json files of approx. 1GB each but getting errors on a few.

**Error description:**
The error log indicates an ArrayIndexOutOfBoundsException during the batch feeding process. The exception is thrown when attempting to copy an array, and the destination index exceeds the array`s bounds.  This issue occurs within the JsonFileFeeder class, specifically in the batchFeed method.

**Error log:**

[FeedThread-14] JsonFileFeeder - ERROR: Error while batch feeding file: local/documents/slice_doc2_1_00004.json java.util.concurrent.CompletionException: ai.vespa.feed.client.FeedException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 150862649 out of bounds for byte[134217728]
    at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
    at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
Caused by: ai.vespa.feed.client.FeedException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 150862649 out of bounds for byte[134217728]
    at ai.vespa.feed.client.JsonFeeder.wrapException(JsonFeeder.java:229) ~[vespa-feed-client-api-8.301.19.jar:?]
    at ai.vespa.feed.client.JsonFeeder.lambda$feedMany$7(JsonFeeder.java:180) ~[vespa-feed-client-api-8.301.19.jar:?]
    ... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 150862649 out of bounds for byte[134217728]
    at java.lang.System.arraycopy(Native Method) ~[?:?]
    at ai.vespa.feed.client.JsonFeeder$RingBufferStream.expand(JsonFeeder.java:307) ~[vespa-feed-client-api-8.301.19.jar:?]
    at ai.vespa.feed.client.JsonFeeder$RingBufferStream.read(JsonFeeder.java:269) ~[vespa-feed-client-api-8.301.19.jar:?]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:264) ~[jackson-core-2.16.1.jar:2.16.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2501) ~[jackson-core-2.16.1.jar:2.16.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipString(UTF8StreamJsonParser.java:2677) ~[jackson-core-2.16.1.jar:2.16.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:758) ~[jackson-core-2.16.1.jar:2.16.1]
    at ai.vespa.feed.client.JsonFeeder$OperationParserAndExecutor.next(JsonFeeder.java:449) ~[vespa-feed-client-api-8.301.19.jar:?]
    at ai.vespa.feed.client.JsonFeeder.feedMany(JsonFeeder.java:157) ~[vespa-feed-client-api-8.301.19.jar:?]
    at ai.vespa.feed.client.JsonFeeder.feedMany(JsonFeeder.java:139) ~[vespa-feed-client-api-8.301.19.jar:?]
 

**Environment:**
Podman: version 4.4.1
Vespa-> 8.301.19
On-prem host OS: Linux 8.8

**Comment by asutoshprasad** [comment]
Yes, we have large documents in JSON files. I will test the fix with the next release. Thanks

**Comment by nehajatav** [comment]
@arnej27959  can you share the fix version please?
cc: @bratseth

**Comment by bratseth** [comment]
Fixed in 8.416
