### ISSUE TITLE
Unstable Travis build

### ISSUE THREAD

**Issue by mpolden** [vespa-engine/vespa#3568]
The Travis build (both master and pull requests) seems to have become unstable over the past few days.

A few examples, all failing in the `orchestrator` module:
- https://travis-ci.org/vespa-engine/vespa/jobs/280739149
- https://travis-ci.org/vespa-engine/vespa/jobs/280402497
- https://travis-ci.org/vespa-engine/vespa/jobs/280372269
- https://travis-ci.org/vespa-engine/vespa/jobs/280339501

PR builds have been very stable so far, but now they fail approximately 1/3 of the time, in my experience.

Additionally, having the "build failing" badge appear on our GitHub front page is unfortunate now that the project is attracting a lot of attention.

FYI @bjorncs @hakonhall

**Comment by hakonhall** [comment]
Going through the failed Travis builds, there are between 0 and 4 successful non-cancelled builds between each fail (0, 1, 1, 3, 3, and 4). It's mostly failing on orchestrator module, with a JVM exit with no further info (6), but is sometimes also failing with what may be related (3, one explicitly says Travis is unable to allocate memory).

Given this frequency, I'm guessing this started ~3 days ago somewhere around the time enforce-container-dependencies PR started going in, which required a maven upgrade to 3.3.9, but that was reverted @bjorncs ?

The last changes in orchestrator I would have suspected went in ~10 days ago.

**Comment by bjorncs** [comment]
Yeah, we reverted back to Maven 3.0.5. It could be the case that the surefire plugin is running out of heap space. Are the orchestrator unit tests known for consuming a lot of memory?

**Comment by hakonhall** [comment]
Some tests uses a curator test zookeeper instance - perhaps that's using a lot of memory. Could we run with more debug info on the Maven run to confirm it's java heap issue?

**Comment by mpolden** [comment]
There's also some instability in the C++ build, which fails building some ZooKeeper things. Example: https://travis-ci.org/vespa-engine/vespa/jobs/281224379

**Comment by mpolden** [comment]
And https://travis-ci.org/vespa-engine/vespa/jobs/281202332 and https://travis-ci.org/vespa-engine/vespa/jobs/281190305 and https://travis-ci.org/vespa-engine/vespa/jobs/281166179 and https://travis-ci.org/vespa-engine/vespa/jobs/280865969.

**Comment by aressem** [comment]
I'm fixing the zookeeper issues. This is related to a bad vespa-dev docker image that was missing the zookeeper packages.

**Comment by bjorncs** [comment]
The JVM is exiting with exit code 137 on either _ApplicationSuspensionResourceTest_ or _ZookeeperStatusServiceTest_. I could not find any trace where _System.exit_ is called (tried to detect unexpected calls to _System.exit_ through _SecurityManager_ with no success). Output below generated with `mvn -nsu -X test` in _ochestrator_ module, with surefire version 2.20.1 (which has improved debug output over 2.19).

```
[INFO] Running com.yahoo.vespa.orchestrator.resources.HostResourceTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.55 s - in com.yahoo.vespa.orchestrator.resources.HostResourceTest
[INFO] Running com.yahoo.vespa.orchestrator.resources.ApplicationSuspensionResourceTest
[WARNING] Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 9.331 s - in com.yahoo.vespa.orchestrator.resources.ApplicationSuspensionResourceTest
[INFO] Running com.yahoo.vespa.orchestrator.policy.HostedVespaPolicyTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.073 s - in com.yahoo.vespa.orchestrator.policy.HostedVespaPolicyTest
[INFO] Running com.yahoo.vespa.orchestrator.policy.HostedVespaClusterPolicyTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 s - in com.yahoo.vespa.orchestrator.policy.HostedVespaClusterPolicyTest
[INFO] Running com.yahoo.vespa.orchestrator.OrchestratorUtilTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in com.yahoo.vespa.orchestrator.OrchestratorUtilTest
[INFO] Running com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 28, Failures: 0, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.169s
[INFO] Finished at: Mon Oct 02 17:01:59 UTC 2017
[INFO] Final Memory: 22M/284M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project orchestrator: There are test failures.
[ERROR]
[ERROR] Please refer to /root/vespa/orchestrator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project orchestrator: There are test failures.

Please refer to /root/vespa/orchestrator/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
Error occurred in starting fork, check output in log
Process Exit Code: 137
Crashed tests:
com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
Error occurred in starting fork, check output in log
Process Exit Code: 137
Crashed tests:
com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: There are test failures.

Please refer to /root/vespa/orchestrator/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
Error occurred in starting fork, check output in log
Process Exit Code: 137
Crashed tests:
com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
Error occurred in starting fork, check output in log
Process Exit Code: 137
Crashed tests:
com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:235)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:112)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:354)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:984)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /root/vespa/orchestrator && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /root/vespa/orchestrator/target/surefire/surefirebooter7789100222818791915.jar /root/vespa/orchestrator/target/surefire 2017-10-02T17-01-41_121-jvmRun1 surefire3360037546223410835tmp surefire_01378900282442887882tmp
Error occurred in starting fork, check output in log
Process Exit Code: 137
Crashed tests:
com.yahoo.vespa.orchestrator.status.ZookeeperStatusServiceTest
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mpolden** [comment]
Exit code 137 translates to 9 (137-128=9), SIGKILL. Maybe we're hitting the memory limit on Travis and the kernel's OOM killer kills the process?

**Comment by bjorncs** [comment]
I doubt it is an OoM issue. I was able to reproduce it on a Docker container on my developer machine, with 8GB RAM and 2GB as default max heap size inside the container.

**Comment by mpolden** [comment]
Nice, in case the kernel killed it there should be message in `dmesg`.

**Comment by bjorncs** [comment]
Me and @hakonhall had a debugging session yesterday. We identified {{ApplicationSuspensionResourceTest}} as the culprit. There is a JNI orJVM OoM issue somewhere triggered by https://github.com/vespa-engine/vespa/blob/master/orchestrator/src/test/java/com/yahoo/vespa/orchestrator/resources/ApplicationSuspensionResourceTest.java#L44 the second time the _@Before_ initializer is executed. {{Application.fromApplicationPackage}} eats up all memory on the host and gets killed by the kernel.
The unit test is now temporarily disabled.
