### ISSUE TITLE
ClientFeederV3 NullPointerException when trying to feed document.

### ISSUE THREAD

**Issue by WeiBanjo** [vespa-engine/vespa#5865]
I am trying to feed document to Vespa using HttpClient. Used `VespaProducerTest.feedJson()` method to feed document. 

I am getting `NullPointerException` on server side and no failure callback received on client side.

Please advise.

## Stacktrace

```
1526325756.283000 WARNING : Container.com.y Unhandled exception while feeding: NullPointerException
exception=
java.lang.NullPointerException
	at com.yahoo.vespa.http.server.ClientFeederV3.setRoute(ClientFeederV3.java:318)
	at com.yahoo.vespa.http.server.ClientFeederV3.pullMessageFromRequest(ClientFeederV3.java:198)
	at com.yahoo.vespa.http.server.ClientFeederV3.feed(ClientFeederV3.java:231)
	at com.yahoo.vespa.http.server.ClientFeederV3.handleRequest(ClientFeederV3.java:137)
	at com.yahoo.vespa.http.server.FeedHandlerV3.handle(FeedHandlerV3.java:100)
	at com.yahoo.vespa.http.server.FeedHandler.handle(FeedHandler.java:175)
	at com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handle(ThreadedHttpRequestHandler.java:66)
	at com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handleRequest(ThreadedHttpRequestHandler.java:79)
	at com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.processRequest(ThreadedRequestHandler.java:180)
	at com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.run(ThreadedRequestHandler.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

## Producer code snippet
```
import com.yahoo.vespa.http.client.FeedClient;
import com.yahoo.vespa.http.client.FeedClientFactory;
import com.yahoo.vespa.http.client.Result;
import com.yahoo.vespa.http.client.config.*;

import java.util.concurrent.TimeUnit;

import io.prometheus.client.Counter;

public class VespaProducerTest {

  static final Counter VESPA_FEED_SUCCESS_LOG_COUNT = Counter.build()
      .name("vespa_feed_success_log_count")
      .help("vespa_feed_success_log_count")
      .register();

  static final Counter VESPA_FEED_FAILURE_LOG_COUNT = Counter.build()
      .name("vespa_feed_failure_log_count")
      .help("vespa_feed_failure_log_count")
      .register();

  private static final String ENDPOINT_URL = "localhost";
  private static final int ENDPOINT_PORT = 8080;
  private static final boolean ENDPOINT_USE_SSL = false;
  private final FeedClient mFeedClient;

  public VespaProducerTest() {
    Cluster cluster = new Cluster.Builder()
        .addEndpoint(
            Endpoint.create(ENDPOINT_URL, ENDPOINT_PORT, ENDPOINT_USE_SSL)
        )
        .build();
    FeedParams feedParams = new FeedParams.Builder()
        .setDataFormat(FeedParams.DataFormat.JSON_UTF8)
        .setClientTimeout(10, TimeUnit.SECONDS)
        .setServerTimeout(10, TimeUnit.SECONDS)
        .build();
    SessionParams sessionBuilder = new SessionParams.Builder()
        .addCluster(cluster)
        .setFeedParams(feedParams)
        .setConnectionParams(new ConnectionParams.Builder()
            .setDryRun(false)
            .setUseCompression(true).build())
        .build();
    mFeedClient = FeedClientFactory.create(sessionBuilder, new MyResultCallback());
  }

  public void feedJson(String id, String jsonString) {
    mFeedClient.stream(id, jsonString);
  }

  public void shutdown() {
    if (mFeedClient != null) {
      mFeedClient.close();
    }
  }

  private static class MyResultCallback implements FeedClient.ResultCallback {
    public void onCompletion(String docId, Result documentResult) {
      System.out.println(String.valueOf(documentResult.isSuccess()));
      if (documentResult.isSuccess()) {
        VESPA_FEED_SUCCESS_LOG_COUNT.inc();
      } else {
        VESPA_FEED_FAILURE_LOG_COUNT.inc();
      }
    }
  }
}
```

**Comment by jobergum** [comment]
Thank you for the detailed report, Could you please provide the value of the 'jsonString'?

**Comment by jobergum** [comment]
Sorry for the  late reply but your input json document also needs the document id, not just the fields. From http://docs.vespa.ai/documentation/reference/document-json-format.html 

```
{
    "put": "id:music:music::123",
    "fields": {
        "title": "Best of Bob Dylan"
    }
}
```
We'll improve server side input validation in such cases where there is no document id found in the payload or an empty payload "" or '{}'.

**Comment by WeiBanjo** [comment]
Thanks. It's working now after add id field.

**Comment by bratseth** [comment]
The error message here is beyond abysmal, sorry about that @WeiBanjo. 
Let's use this ticket to add proper validation.

**Comment by bratseth** [comment]
Validation messages fixed in https://github.com/vespa-engine/vespa/pull/5943
