### ISSUE TITLE
model-integration unit tests are language dependent

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#7949]
When setting Norwegian as primary language, unit tests fail - probably as numbers generated have comma: 1,050701:

[ERROR] testMnistImport(ai.vespa.rankingexpression.importer.tensorflow.MnistImportTestCase)  Time elapsed: 0.062 s  <<< ERROR!
java.lang.RuntimeException: Imported function map(join(matmul(join(join(imported_ml_function_test_dnn_hidden1_add, 0.009999999776482582, f(a,b)(a * b)), imported_ml_function_test_dnn_hidden1_add, f(a,b)(max(a, b))), constant(test_dnn_hidden2_weights_read), d3), constant(test_dnn_hidden2_bias_read), f(a,b)(a + b)), f(a)(1,050701 * if(a >= 0, a, 1,673263*(exp(a)-1)))) cannot be parsed as a ranking expression
	at ai.vespa.rankingexpression.importer.tensorflow.MnistImportTestCase.testMnistImport(MnistImportTestCase.java:20)
Caused by: com.yahoo.searchlib.rankingexpression.parser.ParseException: Could not parse 'map(join(matmul(join(join(imported_ml_function_test_dnn_hidden1_add, 0.009999999776482582, f(a,b)(a * b)), imported_ml_function_test_dnn_hidden1_add, f(a,b)(max(a, b))), constant(test_dnn_hidden2_weights_read), d3), constant(test_dnn_hidden2_bias_read), f(a,b)(a + b)), f(a)(1,050701 * if(a >= 0, a, 1,673263*(exp(a)-1))))'
	at ai.vespa.rankingexpression.importer.tensorflow.MnistImportTestCase.testMnistImport(MnistImportTestCase.java:20)
Caused by: com.yahoo.searchlib.rankingexpression.parser.ParseException: 

Works well with English as primary langauge on my Mac

**Comment by bratseth** [comment]
Fixed by https://github.com/vespa-engine/vespa/pull/7969
