### ISSUE TITLE
NPE when using an "equals" node in a query tree

### ISSUE THREAD

**Issue by dazld** [vespa-engine/vespa#8983]
similar to https://github.com/vespa-engine/vespa/issues/8689 - trying out a query which should filter based on an `equals` expression. The following YQL works great: 

```
 "select * from sources * where public = true;"
```

however, when encoded as a tree thus:
```
{
  "select": {
    "where": {
      "equals": [
        "public",
        true
      ]
    }
  }
}

```

get the following NPE and stack trace:
```
java.lang.NullPointerException
	at com.yahoo.search.query.SelectParser.buildRange(SelectParser.java:562)
	at com.yahoo.search.query.SelectParser.buildEquals(SelectParser.java:633)
	at com.yahoo.search.query.SelectParser.lambda$walkJson$0(SelectParser.java:179)
	at com.yahoo.slime.ObjectValue.traverse(ObjectValue.java:97)
	at com.yahoo.search.query.SelectParser.walkJson(SelectParser.java:165)
	at com.yahoo.search.query.SelectParser.buildTree(SelectParser.java:158)
	at com.yahoo.search.query.SelectParser.parse(SelectParser.java:148)
	at com.yahoo.search.query.Model.getQueryTree(Model.java:240)
	at com.yahoo.search.federation.FederationSearcher.cloneFederationQuery(FederationSearcher.java:264)
	at com.yahoo.search.federation.FederationSearcher.search(FederationSearcher.java:244)
	at com.yahoo.search.federation.FederationSearcher.search(FederationSearcher.java:209)
	at com.yahoo.search.federation.FederationSearcher.search(FederationSearcher.java:204)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.searcher.BlendingSearcher.search(BlendingSearcher.java:59)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.search.grouping.GroupingQueryParser.search(GroupingQueryParser.java:39)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.semantics.SemanticSearcher.search(SemanticSearcher.java:88)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.searcher.PosSearcher.search(PosSearcher.java:63)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.searcher.JuniperSearcher.search(JuniperSearcher.java:72)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.search.yql.FieldFilter.search(FieldFilter.java:34)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.search.yql.MinimalQueryInserter.search(MinimalQueryInserter.java:42)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.searcher.FieldCollapsingSearcher.search(FieldCollapsingSearcher.java:102)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.querytransform.PhrasingSearcher.search(PhrasingSearcher.java:60)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.prelude.statistics.StatisticsSearcher.search(StatisticsSearcher.java:208)
	at com.yahoo.search.Searcher.process(Searcher.java:133)
	at com.yahoo.processing.execution.Execution.process(Execution.java:112)
	at com.yahoo.search.searchchain.Execution.search(Execution.java:510)
	at com.yahoo.search.handler.SearchHandler.searchAndFill(SearchHandler.java:342)
	at com.yahoo.search.handler.SearchHandler.search(SearchHandler.java:395)
	at com.yahoo.search.handler.SearchHandler.handleBody(SearchHandler.java:280)
	at com.yahoo.search.handler.SearchHandler.handle(SearchHandler.java:190)
	at com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handle(ThreadedHttpRequestHandler.java:65)
	at com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handleRequest(ThreadedHttpRequestHandler.java:78)
	at com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.processRequest(ThreadedRequestHandler.java:180)
	at com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.run(ThreadedRequestHandler.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by jobergum** [comment]
The POST search api is described here https://docs.vespa.ai/documentation/search-api.html 

It expects "yql": "select * from sources * where public = true;" and afaik a tree like encoding is not supported.

**Comment by bratseth** [comment]
We forgot to add boolean parsing to the select parser, sorry about that.
Fixed in https://github.com/vespa-engine/vespa/pull/8984, should be in tomorrow's release, if one goes through.
